openapi: 3.0.1
info:
  title: IO APIs, shared specs
  version: "0.1"
servers:
- url: /
paths:
  /dummy:
    get:
      responses:
        200:
          description: ok
          content: {}
components:
  schemas:
    $ref: definitions.yaml
