swagger: "2.0"
info:
  title: "IO APIs, shared specs"
  version: "0.1"
paths:
  "/dummy":
    get:
      responses:
        "200":
          description: "ok"
  "/broken":
    get:
      parameters:
        - name: invalid_param
          in: invalid_location
definitions:
  $ref: definitions.yaml
