openapi: 3.0.1
info:
  title: LolliPoP Model Definitions
  description: The definitions of the models needed by the LolliPoP protocol.
  version: 1.0.0

# Dummy unused endpoint
paths:
  /dummy:
    get:
      responses:
        "200":
          description: "ok"

components:
  schemas:
    
    AssertionType:
      type: string
      enum:
        - SAML
        - OIDC
    
    AssertionRefSha256:
      type: string
      pattern: "^(sha256-[A-Za-z0-9-_=]{1,44})$"

    AssertionRefSha384:
      type: string
      pattern: "^(sha384-[A-Za-z0-9-_=]{1,66})$"

    AssertionRefSha512:
      type: string
      pattern: "^(sha512-[A-Za-z0-9-_=]{1,88})$"

    AssertionRef:
      oneOf:
        - $ref: "#/components/schemas/AssertionRefSha256"
        - $ref: "#/components/schemas/AssertionRefSha384"
        - $ref: "#/components/schemas/AssertionRefSha512"

    OperationId:
      type: string
      minLength: 1